# Generated by Django 4.2.7 on 2024-04-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0059_issue_time_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration', models.SmallIntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_progress_history', to='db.issue')),
            ],
        ),
    ]
