# Generated by Django 4.2.7 on 2024-04-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0058_alter_moduleissue_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.FloatField(null=True)),
                ('ended_at', models.FloatField(null=True)),
                ('duration', models.SmallIntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_progress_history', to='db.issue')),
            ],
        ),
    ]
